### ISSUE TITLE
WitRecordingSession.h missing

### ISSUE THREAD

**Issue by chendo** [wit-ai/wit-ios-sdk#46]
The 4.1.0 release of the SDK tries to import `WITRecordingSession.h` which doesn't exist in the zip file.

**Comment by gruhls508** [comment]
Just ran into this along with a member of my team

**Comment by Euricodev** [comment]
same problem here. If anyone has a clue how to solve this i'll apretiate it.

**Comment by Martin1982** [comment]
I can't build my project either with the released SDK. I guess something needs to be fixed. But I don't know how to build the project to the distributable package. Can anyone elaborate on that?

When cloning the project and building it it works just fine.

**Comment by dealaus** [comment]
So is this not being addressed?

**Comment by dealaus** [comment]
I found a fix. Just remove '#import "WitRecordingSession.h"' from the Wit.h file in the Headers folder. It seems they forgot to remove this in the newest release.

**Comment by smbae** [comment]
just move .h files from 'wit-ios-sdk-4.1.0' --> 'Wit' folder

**Comment by hactar** [comment]
This is fixed in the current version.
