### ISSUE TITLE
Slow result times with speech recognition

### ISSUE THREAD

**Issue by burkaygur** [wit-ai/wit-ios-sdk#49]
Getting a speech to text result from the backend has increased significantly. I am measuring about 6-7 seconds for a given query vs. the 1-2 second query response time from the Nuance SDK. Any ideas why? Does the SDK stream the audio real time as its recording it? Looks like it is, so I cannot figure out why the results would be so slow...

**Comment by l5t** [comment]
Thanks for reporting. You're right. The latency of the speech API has increased since our maintenance. We are investigating and will report back asap. Sorry for the inconvenience this may cause.

**Comment by burkaygur** [comment]
Thank you very much! Looking forward to it, as I have some production apps in the pipeline waiting to be released.

**Comment by burkaygur** [comment]
I have been testing api.ai and Nuance SDK. I get results almost immediately. Any estimates on when I should test wit.ai STT again?

**Comment by l5t** [comment]
I would say in 2-3 weeks.

**Comment by burkaygur** [comment]
Looking forward to it! I will check back next week.

**Comment by burkaygur** [comment]
Just did another test. Still extremely slow. Any updates?

**Comment by l5t** [comment]
Hi,
We pushed a fix this afternoon that should improve the response time. Can you test again when you have time and report if you see improvement?
Thanks
Laurent

**Comment by burkaygur** [comment]
Last time I checked there was no observable difference. Around 5-7 seconds with WiFi.

**Comment by alexanderkjeldaas** [comment]
What's the status of this?

**Comment by hactar** [comment]
The current sdk version has made improvements to speech recognition time by using a different encoding in low bandwidth mode, and using iOS built in speech recognition in iOS 10. Closing, please reopen if the issue persists.
