### ISSUE TITLE
Problem while installing Wit

### ISSUE THREAD

**Issue by Qwert321123** [wit-ai/wit-ios-sdk#51]
Hi guys. I've tried to install Wit.ai on my Ubuntu 12.04. It's clean, i only have here only basic programs (libcur and libsox are ofc installed). 
I used code from this site: https://wit.ai/docs/python/1.0.0/quickstart
And when I'm trying to use pip, or clone frome github i get error:
"Running setup.py install for wit
    Retrieving platform-specific libwit library... libwit-64-linux.a
    error: No such file or directory
"
and i have no idea what the hell is going on.. Is this caused by my ubuntu? Or what? 

I'll be grateful for any help

**Comment by erb325** [comment]
I do not see how this is an issue for the Wit-ios-sdk.

**Comment by hactar** [comment]
Closing as this is not part of the iOS SDK. I'm guessing you are looking for https://github.com/wit-ai/pywit
