### ISSUE TITLE
simple way to mark requests?

### ISSUE THREAD

**Issue by bubakazouba** [wit-ai/wit-ios-sdk#52]
I am trying to use mark my messages using the "msg_id" parameter that can be sent to wit and wit will send it back again. (see: https://wit.ai/docs/http/20141022#get-intent-via-speech-link).

I can see that in WitUploader.m --> startRequestWithContext, the url being formed would only contain the "context" (if it wasn't nil), is there something am I missing? Or is there just an easier way to "mark" my messages?

**Comment by dudu13** [comment]
I am also having the same problem, that would be great if you added it to the sdk.

**Comment by tielur** [comment]
I haven't used it but would the start method with the customData work?
```objective-c
- (void)start: (id)customData;
```
According to the API
> This is how you should link a request to a response, if needed.

**Comment by bubakazouba** [comment]
customData is always the WITMicButton (line 238/243 WITMicButton.m)

**Comment by hactar** [comment]
When using the new converseAPI you can use the WitSession's customData to pass around data that you do not want sent to the server, so you could use this to mark your query.
