### ISSUE TITLE
FallBack intent

### ISSUE THREAD

**Issue by thakurdDev** [wit-ai/wit-ios-sdk#75]
Hi...

is there any default fallback intent in wit.ai like api.ai  
What i want here : When no match found from entities fallback intent should response.

**Comment by hactar** [comment]
This is a frequently asked feature but falls outside the scope of the iOS sdk, I'd suggest discussing it here: https://github.com/wit-ai/wit/issues/335

My current workaround for this is that I have an intent called fallback which I train with everything the user says that falls out of the scope of the app, and by checking the confidence value, and if its too low also triggering the fallback code in my app.
