### ISSUE TITLE
Podspec Version is broken

### ISSUE THREAD

**Issue by thinkrad** [wit-ai/wit-ios-sdk#80]
The Podspec is listed as being 4.2.0, but still points to the commit tagged 4.1.0. It doesn't work.

```
Pod::Spec.new do |s|
  s.name         = "Wit"
  s.version      = "4.2.0"

...

  s.source       = { :git => "https://github.com/wit-ai/wit-ios-sdk.git", :tag => "4.1.0" }
```

**Comment by hactar** [comment]
Thanks. The current commit fixes this. It still needs to be pushed to the trunk by someone from the wit team, see https://github.com/wit-ai/wit/issues/454

**Comment by hactar** [comment]
podspec has been pushed to trunk. Works for me, thanks again for reporting.
