### ISSUE TITLE
WitMicButton unregistering a not registered observer

### ISSUE THREAD

**Issue by gerlandiolucena** [wit-ai/wit-ios-sdk#81]
In WitMicButton.m at 302 line has a removeObserver function that tries to unregister a observer that was not registered in this version (4.2.0), when the ViewController was deallocated the app crashes.

Cannot remove an observer <WITMicButton 0x15e679ba0> for the key path "frame" from <WITRecorder 0x15e718530> because it is not registered as an observer.'

**Comment by hactar** [comment]
Good catch - will fix it this weekend.
